//
//  MainWindow.h
//  Renderer
//
//  Created by Raphael Kargon on 6/6/14.
//  Copyright (c) 2014 Raphael Kargon. All rights reserved.
//

#ifndef _RENDERER_UI_MAINWINDOW_H
#define _RENDERER_UI_MAINWINDOW_H

#include <QMainWindow>

#include <memory>

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow {
  Q_OBJECT

public:
  MainWindow(QWidget *parent = nullptr);
  ~MainWindow() = default;

private:
  // Auto-generated by Qt. DO NOT RENAME!
  Ui::MainWindow *ui;
};

#endif // _RENDERER_UI_MAINWINDOW_H
